@host=http://localhost:8080
@id=27d9e168-ea7e-4cf0-bcaf-4520981e8a18

### create
POST {{host}}/api/v1/users
Content-Type: application/json

{
  "email": "user3@mail.com",
  "password": "user3"
}

### list all
GET {{host}}/api/v1/users

### get by id
GET {{host}}/api/v1/users/{{id}}

### update password
PATCH  {{host}}/api/v1/users/{{id}}
Content-Type: application/json

{
  "password_old": "user3",
  "password_new": "1234"
}
### delete by id
DELETE {{host}}/api/v1/users/{{id}}