@host=http://localhost:8080

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxMkBtYWlsLmNvbSIsImV4cCI6MTY1OTY4MDM4NiwiaWF0IjoxNjU5NjgwMDg2LCJyb2xlIjoiYWRtaW4iLCJzdWIiOiJhYzQwOWI3Yy00OWFhLTQxNjAtODBiZi1lMmU0Y2E4OWE2YzQiLCJ1c2VyX2lkIjoiNzM0OWM4OTItZGYyOS00NWM5LWJkODgtNGU1MGRmZmY0ZTFhIn0.woXYTlZpldU57FnAIddbJn-wSjq6QIzp_WUWJY9b5bc


### register
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

### login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

### profile
GET {{host}}/api/v1/auth/profile
Authorization: Bearer {{token}}

### update profile
PATCH  {{host}}/api/v1/auth/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password_old": "1234",
  "password_new": "user"
}
