@host=http://localhost:8080

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJpYXQiOjE2NTk0OTc5MDEsInN1YiI6IjViNDM3Y2NjLWNkZjUtNDZiZS1hOWNhLWU3NmY0NWY0NTEzYSJ9.tnyWPVzPUK-HhEmeI4p0BFNLy-YZUKoZB-OYxSts9iQ


### register
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

### login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

### profile
GET {{host}}/api/v1/auth/profile/123?q=1
Authorization: Bearer {{token}}
